### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by MAGistR-bit** [zmtprofile/Godot_Pixel_Platformer#2]
Hello, @zmtprofile!
Cool project! Buddy, are you looking for friends? 
Can we work together? I am a beginner, so any experience will be useful for me. 
I'm learning Java. What programming languages do you know?
Have a nice day!

**Comment by zmtprofile** [comment]
Hi 
It is really nice to have some friends i can work together with. 
I know java and few other languages. I used java for android project. 
This is a godot project i created for code along tutorial and add extra stuff after tutorial is done. 
do you have any project in mind to work on?
I assume you are interested in godot or game dev since you are looking this repository.
@MAGistR-bit

**Comment by MAGistR-bit** [comment]
Hi, @zmtprofile! 
Sorry for the long answer! I couldn't answer because I was sick. No, there are no ideas for the project yet. 
The thought that comes to mind... Try to solve problems together on LeetCode, Codewars. 
What about you? Do you have any ideas?

**Comment by zmtprofile** [comment]
Hi. 
can you tell me more detail about your idea? Like is there any plan for the front end(web etc)?
Also, I think if there is file upload and sharing involved, we are going to need cloud space for that. And storage can be costly. 
if you want to do it let me know more details. 
If you are interested in game development, how about we start with a really simple game? something playable. and we make improvements later on and maybe participate in game gems in the future.  I don't have experience with game dev, so it would be a new and fun experience.

**Comment by zmtprofile** [comment]
And I hope you are feeling well and in good health now. 
@MAGistR-bit

**Comment by MAGistR-bit** [comment]
Hi! 
I hear you, ZAY. You want to develop a simple game. 
Okay, let's try it!!!  
Is the Java language suitable for game development?

**Comment by MAGistR-bit** [comment]
Hi, @zmtprofile! How are you?

**Comment by zmtprofile** [comment]
Hi
sry for the late reply. I am in the place with limited access to internet right now. You can use Java for game development but it is not popular choice. Game engines like unity and godot are more common choice for beginners.Unity use c# which syntax are similar with Java.
You can create a gihub repo and add me as contributor or I will create one. Your choice.

**Comment by MAGistR-bit** [comment]
Hello, buddy! I looked at the C# syntax, it's similar to Java, but...
I won't be able to write in it because I have no experience with this language. Yes... And I've never worked with an Godot.
Maybe you have another project that will be related to Java?
@zmtprofile, I await your answer!

**Comment by MAGistR-bit** [comment]
> sorry for being late reply. if you want to use java for game dev. jMonkeyEngine and libgdx would be the choice for engine.

Hi! We can try! 
@zmtprofile, are you going to write in Java too? If you use a different language, then... I'm afraid we won't be able to understand each other.
We need the same technology stack.

**Comment by zmtprofile** [comment]
Both engines are java engines. so don't worry. I will be using the same language.
